services:
  java_db:
    container_name: java_db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES-USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}